import { t } from '@lingui/macro'
import Help from 'components/help'
import LeafIcon from 'components/icons/LeafIcon'
import ShieldIcon from 'components/icons/ShieldIcon'
import StackedChainLogo from 'components/icons/StackedChainLogo'
import TreeIcon from 'components/icons/TreeIcon'
import { ArrowUpRight } from 'lucide-react'
import Skeleton from 'react-loading-skeleton'
import { Box, Flex, Grid, Text } from 'theme-ui'
import { formatCurrency } from 'utils'
import {
  CHAIN_TO_NETWORK,
  capitalize,
  supportedChainList,
} from 'utils/constants'
import useProtocolMetrics from '../hooks/useProtocolMetrics'
import HistoricalTVL from './HistoricalTVL'

const ProtocolStats = () => {
  const {
    data: {
      marketCap,
      rsrLockedUSD,
      rTokenAnnualizedRevenue,
      rsrStakerAnnualizedRevenue,
    },
    isLoading,
  } = useProtocolMetrics()

  const statInfo = [
    {
      icon: <TreeIcon />,
      value: formatCurrency(marketCap, 1, {
        notation: 'compact',
        compactDisplay: 'short',
      }),
      valueLong: formatCurrency(marketCap, 0),
      title: t`RToken Market Cap`,
      tooltip: t`The total value of all RToken in circulation`,
    },
    {
      icon: <ShieldIcon />,
      value: formatCurrency(rsrLockedUSD, 1, {
        notation: 'compact',
        compactDisplay: 'short',
      }),
      valueLong: formatCurrency(rsrLockedUSD, 0),
      title: t`First-loss RSR Capital`,
      tooltip: t`The total value of all RSR staked in the protocol`,
    },
    {
      icon: <LeafIcon />,
      value: formatCurrency(rTokenAnnualizedRevenue, 1, {
        notation: 'compact',
        compactDisplay: 'short',
      }),
      valueLong: formatCurrency(rTokenAnnualizedRevenue, 0),
      title: t`Annualized RTokens Revenue`,
      tooltip: t`The projected annual revenue generated by the protocol for RToken holders, calculated using the current APY and TVL of the listed RTokens.`,
    },
    {
      icon: <LeafIcon />,
      value: formatCurrency(rsrStakerAnnualizedRevenue, 1, {
        notation: 'compact',
        compactDisplay: 'short',
      }),
      valueLong: formatCurrency(rsrStakerAnnualizedRevenue, 0),
      title: t`Annualized RSR Stakers Revenue`,
      tooltip: t`The projected annual revenue generated by the protocol for RSR stakers, calculated using the current RSR staker APY and the amount of staked RSR for the listed RTokens.`,
    },
  ]

  return (
    <Grid
      columns={['1fr 1fr 1fr 1fr', '1fr 1fr']}
      sx={{
        overflowX: 'auto',
        '::-webkit-scrollbar': {
          display: 'none',
        },
        gap: 0,
      }}
    >
      {statInfo.map(({ title, value, valueLong, icon, tooltip }, index) => (
        <Box
          key={title}
          variant="layout.verticalAlign"
          sx={{
            display: 'flex',
            flexDirection: ['column', 'row'],
            alignItems: ['start', 'center'],
            borderTop: ['none', index < 2 ? '1px solid' : 'none'],
            borderRight: ['none', index % 2 === 0 ? '1px solid' : 'none'],
            borderBottom: ['none', '1px solid'],
            borderColor: ['darkBorder', 'darkBorder'],
            gap: [0, 3],
            py: 4,
            pl: [index === 0 ? 4 : 3, 4],
            pr: [index === statInfo.length - 1 ? 4 : 3, 4],
            pb: [3, 4],
            minWidth: ['auto', 0],
          }}
        >
          {icon}
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              flexGrow: 1,
              mt: [3, 0],
            }}
          >
            <Box
              variant="layout.verticalAlign"
              sx={{ gap: 2, justifyContent: 'space-between' }}
            >
              <Text
                sx={{
                  color: 'secondaryText',
                  whiteSpace: ['nowrap', 'normal'],
                }}
              >
                {title}
              </Text>
              <Help content={tooltip} sx={{ display: ['flex', 'none'] }} />
            </Box>
            <Box>
              {!isLoading ? (
                <>
                  <Text
                    variant="sectionTitle"
                    sx={{ fontWeight: '700', display: ['none', 'inline'] }}
                  >
                    ${value}
                  </Text>
                  <Text
                    variant="sectionTitle"
                    sx={{ fontWeight: '700', display: ['inline', 'none'] }}
                  >
                    ${valueLong}
                  </Text>
                </>
              ) : (
                <Skeleton height={32} width={84} />
              )}
            </Box>
          </Box>
          <Help content={tooltip} sx={{ display: ['none', 'block'] }} />
        </Box>
      ))}
    </Grid>
  )
}

const HeroHeader = () => {
  return (
    <Box
      variant="layout.verticalAlign"
      pt={[0, 4]}
      px={[3, 4]}
      pb={4}
      sx={{
        borderBottom: ['1px solid', 'none'],
        borderColor: ['border', 'border'],
        justifyContent: 'space-between',
        gap: 2,
        fontSize: [2, 3],
      }}
    >
      <Box
        variant="layout.verticalAlign"
        sx={{
          flexDirection: ['row', 'column'],
          alignItems: ['center', 'flex-start'],
          gap: [0, 2],
        }}
      >
        <StackedChainLogo chains={supportedChainList} />
        <Text>
          <Text sx={{ display: ['none', 'inline'] }}>The </Text>
          <Text color="accentInverted">
            Reserve <Text sx={{ display: ['none', 'inline'] }}>protocol </Text>
          </Text>
          on
          {supportedChainList.map(
            (chainId, index) =>
              ` ${capitalize(CHAIN_TO_NETWORK[chainId])}${
                index >= supportedChainList.length - 2
                  ? index === supportedChainList.length - 1
                    ? ''
                    : ' & '
                  : ','
              }`
          )}
        </Text>
      </Box>
      <Box
        variant="layout.verticalAlign"
        sx={{
          gap: 1,
          cursor: 'pointer',
          ':hover': {
            filter: 'brightness(1.1)',
          },
          display: ['none', 'flex'],
          mt: [0, 'auto'],
        }}
        onClick={() =>
          window.open(
            'https://dune.com/reserve-protocol/reserve-protocol-overview',
            '_blank'
          )
        }
      >
        <Text variant="bold" color="#999">
          Full dashboard
        </Text>
        <ArrowUpRight color="#999" size={16} />
      </Box>
    </Box>
  )
}

const HeroTVL = () => {
  const {
    data: { tvl },
    isLoading,
  } = useProtocolMetrics()

  return (
    <Box
      sx={{
        position: 'absolute',
        top: 0,
        left: 0,
        display: 'flex',
        flexDirection: 'column',
        color: 'accentInverted',
        gap: 1,
      }}
      px={[3, 4]}
      pt={4}
    >
      <Text sx={{ fontSize: 4 }}>TVL in Venice</Text>

      {!isLoading ? (
        <Text variant="bold" sx={{ fontSize: [5, 6] }}>
          ${formatCurrency(tvl, 0)}
        </Text>
      ) : (
        <Box>
          <Box sx={{ display: ['none', 'flex'] }}>
            <Skeleton
              height={52}
              width={300}
              style={{ marginBottom: '16px' }}
            />
          </Box>
          <Box sx={{ display: ['flex', 'none'] }}>
            <Skeleton
              height={40}
              width={200}
              style={{ marginBottom: '16px' }}
            />
          </Box>
        </Box>
      )}
    </Box>
  )
}

const MobileDuneLink = () => {
  return (
    <Box
      pt={1}
      pb={4}
      px={4}
      variant="layout.verticalAlign"
      sx={{
        gap: 1,
        cursor: 'pointer',
        color: 'accentInverted',
        display: ['flex', 'none'],
        justifyContent: 'space-between',
      }}
      onClick={() =>
        window.open(
          'https://dune.com/reserve-protocol/reserve-protocol-overview',
          '_blank'
        )
      }
    >
      <Text variant="bold">Full Dune Dashboard</Text>
      <ArrowUpRight size={16} />
    </Box>
  )
}

// New Landing Section component
const LandingSection = () => {
  return (
    <Box sx={{ 
      backgroundColor: '#1c1c1c', 
      padding: '4rem 0',
      marginBottom: '2rem'
    }}>
      <Box sx={{ 
        maxWidth: '1200px',
        margin: '0 auto',
        padding: '0 1rem'
      }}>
        {/* Hero image */}
        <Box sx={{ 
          width: '100%',
          display: 'flex',
          justifyContent: 'center',
          marginBottom: '4rem'
        }}>
          <Box sx={{ 
            width: '45%',
            minWidth: '320px',
            maxWidth: '700px',
            position: 'relative',
            borderRadius: '0.5rem',
            overflow: 'hidden',
            boxShadow: '0 0 40px 10px rgba(0, 218, 255, 0.15), 0 0 10px 2px rgba(0, 218, 255, 0.2)'
          }}>
            <Box sx={{
              position: 'absolute',
              inset: '-0.5rem',
              backgroundColor: '#00DAFF',
              opacity: 0.2,
              filter: 'blur(1rem)',
              borderRadius: '0.5rem',
              zIndex: 0
            }} />
            <Box sx={{
              position: 'relative',
              zIndex: 1,
              backgroundColor: '#1c1c1c',
              borderRadius: '0.5rem'
            }}>
              <img
                src="/images/hero-orange-blue.webp"
                alt="FinkFi Hero Illustration"
                style={{
                  width: '100%',
                  height: 'auto',
                  objectFit: 'contain',
                  borderRadius: '0.5rem'
                }}
              />
              <Box sx={{
                position: 'absolute',
                inset: 0,
                backgroundImage: 'linear-gradient(to bottom, transparent, rgba(28, 28, 28, 0.8))',
                borderBottomLeftRadius: '0.5rem',
                borderBottomRightRadius: '0.5rem'
              }} />
            </Box>
          </Box>
        </Box>

        {/* Hero content */}
        <Grid columns={[1, null, 2]} gap={4} sx={{ maxWidth: '1100px', margin: '0 auto' }}>
          <Box>
            <Text sx={{ 
              color: 'white',
              fontSize: ['2rem', '2.5rem', '3rem'],
              fontWeight: 500,
              lineHeight: 'tight',
              marginBottom: '1.5rem'
            }}>
              We want money that doesn't inflate like USD, but isn't volatile like Bitcoin.
            </Text>
          </Box>
          <Box>
            <Text sx={{ 
              color: 'white',
              fontSize: '1.125rem',
              marginBottom: '1.5rem'
            }}>
              We believe money should be an index of the world's assets: stocks, bonds, gold, real estate, and more.
            </Text>
            <Text sx={{ 
              color: 'white',
              fontSize: '1.125rem',
              marginBottom: '2rem'
            }}>
              To that end, we're building technology that allows anyone to permissionlessly create and own Decentralized Token Folios (DTFs) — baskets of tokenized crypto assets.
            </Text>
            <Flex sx={{ gap: '1rem' }}>
              <Box sx={{ 
                flex: 1,
                maxWidth: '20rem'
              }}>
                <input
                  type="email"
                  placeholder="Enter your email"
                  style={{
                    backgroundColor: 'transparent',
                    border: '1px solid rgba(255, 255, 255, 0.2)',
                    padding: '0.75rem',
                    borderRadius: '0.375rem',
                    width: '100%',
                    outline: 'none',
                    color: 'white'
                  }}
                />
              </Box>
              <button
                style={{
                  backgroundColor: '#00DAFF',
                  color: 'white',
                  border: 'none',
                  padding: '0.75rem 1.5rem',
                  borderRadius: '0.375rem',
                  fontWeight: 500,
                  cursor: 'pointer'
                }}
              >
                Learn more
              </button>
            </Flex>
          </Box>
        </Grid>
      </Box>
    </Box>
  )
}

const Hero = () => (
  <Box>
    {/* New landing section */}
    <LandingSection />
    
    {/* Original hero content */}
    <Box
      sx={{
        position: 'relative',
        height: '100%',
        overflow: 'hidden',
        minHeight: [560, 480],
      }}
    >
      <Flex
        sx={{
          position: 'relative',
          flexDirection: 'column',
          borderRadius: [0, '14px'],
          backgroundColor: ['none', 'reserveBackground'],
          height: '100%',
          overflow: 'hidden',
        }}
        mx="auto"
      >
        <Box
          sx={{
            position: 'relative',
            display: 'flex',
            flexDirection: 'column-reverse',
            height: '100%',
            overflow: 'hidden',
          }}
        >
          <Box sx={{ display: ['block', 'none'] }}>
            <HeroHeader />
          </Box>
          <Box
            sx={{ position: 'relative', height: '100%', overflow: 'hidden' }}
            px={[2, 3]}
            pt={[2, 3]}
          >
            <HeroTVL />
            <HistoricalTVL />
          </Box>
        </Box>
        <Box sx={{ flexGrow: 1 }}>
          <ProtocolStats />
          <Box sx={{ display: ['none', 'block'] }}>
            <HeroHeader />
          </Box>
        </Box>
        <MobileDuneLink />
      </Flex>
    </Box>
  </Box>
)

export default Hero
